version: 0.1.0

project: liam-test # Update to your project name
jobs:
  basic_tests: # Overall job name
    type: test
    runtime:
      simulator: turtlesim
      framework: ros2:galactic
    timeout: 2 #minutes
    scenarios:
      defaults: # Global to all scenarios, and overriden in specific scenarios.
        subscriptions:
          pose: turtle1/pose
      settings:
        - name: turtle
          ros_testfile: launch_turtle.py
